### PR TITLE
Update version to 0.6.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by mziccard**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
If we intend on doing a purely additive addition (the `fromStream` methods), do we want 0.5.1?

**Comment by mziccard** [comment]
@garrettjonesgoogle I have no preference here. According to semver the PATCH number should be incremented for "backwards-compatible bug fixes" while the MINOR is for when you add functionality in a backwards-compatible manner. To be honest I believe that in other projects we haven't been very strict following semver. I jumped to `0.6.0-SNAPSHOT` following instructions at [RELEASING.md](https://github.com/google/google-auth-library-java/blob/master/RELEASE.md#deploy-to-sonatype):

> unless it's a bugfix release, we update from 0.4.0 to 0.5.0-SNAPSHOT

**Comment by garrettjonesgoogle** [comment]
Well in general, I think < 1.0 is kind of fuzzy under semver anyway. I guess since this is noted in RELEASING.md, let's go ahead with 0.6.0. LGTM

**Pull request merged**
