### PR TITLE
Bumping google-http-client version

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
cc @elharo and @saturnism :-) (this is only the first step in the dependency pachinko machine)

**Comment by elharo** [comment]
Tests failed. Probably not related but this should probably be fixed first:


[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project google-auth-library-parent: Execution checkstyle of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by garrettjonesgoogle** [comment]
The mac job is failing for an unrelated reason - I have no idea why:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project google-auth-library-parent: Execution checkstyle of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]

**Comment by garrettjonesgoogle** [comment]
I reran the mac build (which is the one that failed) and it failed again...

**Comment by garrettjonesgoogle** [comment]
Well, bumping checkstyle fixed the mac build. Maybe there was some weird dependency interaction caused by the bump of http-client - but it's fixed now!

**Comment by elharo** [comment]
FYI, I don't see the guava-jdk5 to guava switch? Is that inside the new version of http-client?

**Comment by garrettjonesgoogle** [comment]
Yes the switch is in http-client: https://github.com/google/google-http-java-client/commit/7b0c01c3c8c07a4d8a5642b9c73386f73c8e661e - which was released in 1.24.1.

**Comment by garrettjonesgoogle** [comment]
Hmm after more research, I found that google-http-client's dependency on guava-jdk5 was `provided`, so it wasn't actually polluting the dependency tree; it turns out that it is google-api-client that has the `compile` dependency on guava-jdk5. Thus, the present PR doesn't change the guava-jdk5 problem. It's good to get the version bumped though!

**Pull request merged**
