### PR TITLE
 Added proxy support for OAuth2 requests.

### PR DESCRIPTION
**Pull request by bullet-tooth**
Implemented proxy support for HTTP and SOCKS.
Fix for issue #127

### CODE REVIEW

**Comment by lesv** [comment]
@garrettjonesgoogle This is probably needed for some Enterprise environments, but we should get an expert to review as this might provide a vector for attack.  (I suspect it's Ok, as one would need access to the machine this code was running on, but I may not be thinking of a case.)

**Comment by lesv** [comment]
@bullet-tooth Is this still important to you?

**Comment by bullet-tooth** [comment]
Hi @lesv . We're using dev version with implemented proxy. So if you think that our case very rare and could cause security issues you can discard this PR.

**Comment by lesv** [comment]
@jonparrott FYI
@bullet-tooth I'm going to close this for now.  I actually think this is a much bigger issue that we should address for all our client libraries.  This is an issue for many developers who need to use a proxy inside their companies.

**Pull request closed without merging**
